disabled_rules:
- identifier_name
- multiple_closures_with_trailing_closure
- empty_enum_arguments
- explicit_top_level_acl
- conditional_returns_on_newline
- closure_end_indentation
- discouraged_optional_collection
- explicit_enum_raw_value
- explicit_type_interface
- fatal_error_message
- file_header
- lower_acl_than_parent
- no_extension_access_modifier
- no_grouping_extension
- multiline_arguments
- strict_fileprivate
- switch_case_on_newline
- trailing_closure
- large_tuple
- explicit_acl
- attributes
- let_var_whitespace

opt_in_rules:
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- conditional_returns_on_newline
- contains_over_first_not_nil
- discouraged_object_literal
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_count
- empty_string
- explicit_acl
- explicit_enum_raw_value
- explicit_init
- explicit_top_level_acl
- explicit_type_interface
- extension_access_modifier
- fatal_error_message
- file_header
- first_where
- force_unwrapping
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- let_var_whitespace
- literal_expression_end_indentation
- multiline_arguments
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- no_grouping_extension
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_action
- private_outlet
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
- strict_fileprivate
- switch_case_on_newline
- trailing_closure
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- vertical_parameter_alignment_on_call
- yoda_condition

included:
  - ImageTransition
  - Demo

# Lint対象から除外するパス
excluded:

line_length:
- 200   # warning
- 300   # error

type_body_length:
- 400   # warning
- 600   # error

file_length:
- 500   # warning
- 1000  # error

function_body_length:
- 100   # warning
- 200   # error

type_name:
min_length: 3
max_length:
warning: 40
error: 50
excluded:

identifier_name:
min_length: # only min_length
error: 2 # only error
excluded: # excluded via string array
- id
- URL
reporter: "xcode"

custom_rules:
  final_class:
    included: "./.*\\.swift"
    name: "Final Class"
    regex: "^(private |fileprivate |internal |public |open )class"
    message: "Final Class"
    severity: error
